[package]
name = "auraclient-api"
version = "0.1.0"
edition = "2021"

[dependencies]
minreq = { version = "2.13.2", features = ["https", "urlencoding", "json-using-serde"] }
mongodb = { version = "3.2.1", features = ["sync"] }
serde = { version ="1.0.218", features = ["derive"] }
